name: Testing Sandbox size trimming workflow

on:
  workflow_dispatch:

jobs:
  trim-sandboxes:
    runs-on: ubuntu-latest

    steps:
      - name: trim sandboxes
        uses: veracode/github-actions-integration-helper@v0.1.8
        with:
          appname: 'test trim'
          action: trim-sandboxes
          trim_to_size: 2
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}



