name: Veracode Policy Scan

on:
  workflow_call:
    inputs:
      create-sandbox:
        description: Whether to create the sandbox if it does not exist
        required: false
        default: false
        type: boolean
      sandbox-name:
        description: The name of the sandbox to create
        required: false
        default: ""
        type: string
      version:
        description: The name or version number of the build - used to name the scan
        required: false
        default: "${{ github.run_id}}-${{ github.run_attempt}}"
        type: string
      policy-name:
        description: The name of the Veracode policy to apply
        required: false
        default: "Qantas Group Policy"
        type: string

env:
  create-sandbox: ${{ inputs.create-sandbox && inputs.create-sandbox || false }}
  sandbox-name: ${{ inputs.sandbox-name && inputs.sandbox-name || '' }}
  version: ${{ inputs.version && inputs.version || format('{0}-{1}', github.run_id, github.run_attempt) }}

jobs:
  policy_scan:
    runs-on: ubuntu-latest
    name: Veracode Policy Scan

    concurrency:
      group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java for Veracode Policy Scan
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          overwrite-settings: false

      - name: Get archive from build workflow
        id: download-built-artifact
        uses: actions/download-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory

      - name: Veracode Upload and Scan Action
        uses: veracode/uploadandscan-action@v0.1.6
        id: upload_and_scan
        with:
          appname: ${{ github.repository }}
          createprofile: true
          policy: ${{ inputs.policy-name }}
          version: ${{ env.version }}
          filepath: "${{ steps.download-built-artifact.outputs.download-path }}/veracode.zip"
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          scantimeout: 60
          failbuild: true
          # Cannot be used in all multi-module projects because it causes failures if there are dependencies
          # see https://github.com/veracode/uploadandscan-action/issues/8
          # include: '*'
          deleteincompletescan: true
          sandboxname: ${{ env.sandbox-name }}
          createsandbox: ${{ env.create-sandbox }}
